name: build-and-test

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  build-and-test-build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/sat-cam.git
        lfs: true

    - name: clone docker
      run: |
        git clone https://github.com/dogusyuksel/embedded_docker.git docker
        cp -rf docker/* .

    - name: Remove unnecessary files
      run: |
        ./free_space.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: Dockerfile
        pull: true
        push: false
        provenance: false

    - name: Build Library
      run: |
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/libsatcam && ./build.sh"

#    - name: Test Library
#      run: |
#        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/libsatcam && ceedling test:all"

    - name: Build Imager
      run: |
        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/imager_demo && ./build.sh"

#    - name: Build Client
#      run: |
#        ./docker/sudo_run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/camera_ctl && ./build.sh"
    
#    - name: flake8
#      run: |
#         echo "'isort .' can be executed if needed"
#         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/post_process && flake8 --max-line-length=120"
